import { useCallback, useEffect, useState } from 'react';
import { Dismiss16Regular } from '@fluentui/react-icons';
import { Button } from '@fluentui/react-components';
import { useVoiceSession } from './hooks';
import { useConversationStore } from './store';
import { Composer, ConversationView, DebugPanel, TopBar, WebConsentCard } from './components';

const looksLikeWebRequest = (text: string) => /\b(busca|buscá|buscar)\b.*\b(web|internet)\b|\ben internet\b|\bweb\b/i.test(text);

export function AppShell() {
  const { toggle } = useVoiceSession(); const consent = useConversationStore((s) => s.pendingWebConsent); const store = useConversationStore(); const [error, setError] = useState('');
  const reportError = (errorCode: string, message: string, turnId = '') => { const qaSessionId = new URLSearchParams(window.location.search).get('qa_session') || ''; void fetch('/api/debug/trace', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ component: 'frontend', event: 'frontend_error_displayed', source: 'human', qa_session_id: qaSessionId, session_id: store.conversationId, turn_id: turnId, generation_id: store.currentGenerationId || '', status: 'error', error_code: errorCode, detail: JSON.stringify({ error_code: errorCode, source_component: 'AppShell', message }) }) }).catch(() => undefined); };
  useEffect(() => { if (store.voiceState !== 'RETRIEVING' && store.voiceState !== 'WAITING_TRANSCRIPT') return; const timeoutMs = store.voiceState === 'WAITING_TRANSCRIPT' ? 15000 : 25000; const timer = window.setTimeout(() => { const message = store.voiceState === 'WAITING_TRANSCRIPT' ? 'No pude entender lo que dijiste. Probá nuevamente.' : 'Tuve un problema al detectar el final de tu frase. Probá de nuevo.'; store.setVoiceState('ERROR'); setError(message); reportError(store.voiceState === 'WAITING_TRANSCRIPT' ? 'STT_TRANSCRIPT_MISSING_AFTER_TURN_COMPLETE' : 'TURN_FINALIZATION_TIMEOUT', message); }, timeoutMs); return () => window.clearTimeout(timer); }, [store.voiceState]);
  useEffect(() => { const params = new URLSearchParams(window.location.search); const code = params.get('e2e_force_error'); if (params.get('e2e_test_mode') !== 'true' || !code) return; const message = code === 'LLM_TIMEOUT' ? 'El modelo tardó demasiado. Probá de nuevo.' : 'Error controlado de prueba.'; store.setVoiceState('ERROR'); setError(message); reportError(code, message, `e2e-${Date.now()}`); }, []);
  const sendText = useCallback(async (text: string) => { store.addUserMessage(text); store.setVoiceState(looksLikeWebRequest(text) ? 'WEB_SEARCHING' : 'RETRIEVING'); const generationId = crypto.randomUUID(); const turnId = `text-${Date.now()}`; store.setGenerationId(generationId); try { const response = await fetch('/api/ask-text', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ question: text, session_id: store.conversationId, turn_id: turnId, generation_id: generationId, source: 'human' }) }); const data = await response.json(); if (data.state === 'ASKING_WEB_PERMISSION') { store.setWebConsent({ query: text }); return; } if (!response.ok) throw new Error(data.error_code || 'UNKNOWN_ERROR'); store.setVoiceState('IDLE'); const id = store.addAssistantMessage(data.answer || 'No encontré evidencia suficiente en la guía local.', data.evidence || [], false); store.finishAssistant(id, data.answer || 'No encontré evidencia suficiente en la guía local.', data.evidence || []); } catch (e) { const message = e instanceof Error ? e.message : 'UNKNOWN_ERROR'; const code = message.includes('LLM') ? 'LLM_TIMEOUT' : message.includes('RAG') ? 'RAG_ERROR' : 'UNKNOWN_ERROR'; reportError(code, message, turnId); setError(message); store.setVoiceState('ERROR'); } }, [store]);
  return <div className="app-shell"><TopBar onNew={() => { store.clearConversation(); setError(''); }} /><ConversationView onSuggestion={sendText} /><footer className="composer-dock"><div className="composer-inner">{consent && <WebConsentCard query={consent.query} onAccept={() => { store.setWebConsent(null); void sendText(`${consent.query} buscá en la web`); }} onReject={() => store.setWebConsent(null)} />}{error && <div className="inline-error"><span>{error}</span><Button appearance="subtle" icon={<Dismiss16Regular />} onClick={() => setError('')} aria-label="Cerrar error" /></div>}<Composer onSend={sendText} onMic={async () => { try { await toggle(); } catch (e) { const message = e instanceof Error ? e.message : 'No pude acceder al micrófono.'; reportError(message.includes('WEBRTC') ? 'WEBRTC_ERROR' : 'UNKNOWN_ERROR', message); setError(message); } }} onSuggestion={sendText} /></div></footer><DebugPanel /></div>;
}
